apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: k8s-demo-app
        imagePullPolicy: Never
        ports:
        - containerPort: 3000

        resources:
          requests:
            cpu: "200m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"

        volumeMounts:
        - mountPath: "/data"
          name: app-storage

      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: app-pvc