name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-validate:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4

      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Docker Build
      run: docker build -t node-app .

    - name: Install kubectl
      uses: azure/setup-kubectl@v4

    - name: Validate Deployment
      run: kubectl apply --dry-run=client --validate=false -f deployment.yaml

    - name: Validate Service
      run: kubectl apply --dry-run=client --validate=false -f service.yaml

    - name: Validate PV
      run: kubectl apply --dry-run=client --validate=false -f pv.yaml

    - name: Validate PVC
      run: kubectl apply --dry-run=client --validate=false -f pvc.yaml

    - name: Validate HPA
      run: kubectl apply --dry-run=client --validate=false -f hpa.yaml